WebApplication1/Models/IncidentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace WebApplication1.Models
{
    public class IncidentType
    {
        [Key]
        public int TypeID { get; set; }

        [Required]
        public string Name { get; set; }

      //  [Required]
        [Display(Name = "Icon")]
        [DataType(DataType.ImageUrl)]
        public string IconUrl { get; set; }
    }
}

WebApplication1/Controllers/IncidentTypesController.cs
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    /// <summary>
    /// Kontroler typu incydentu.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class IncidentTypesController : Controller
    {
        private Context db = new Context();
        /// <summary>
        /// Zapisanie ikony typu incydentu do elementu Blob.
        /// </summary>
        /// <param name="file">Plik ikony.</param>
        /// <returns>Adres do zapisanego pliku.</returns>
        public string saveIconToBlob(HttpPostedFileBase file)
        {
            string azurePath;
            var fileName = Path.GetFileNameWithoutExtension(file.FileName);

            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings["StorageConnectionString"]);
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("markericons");
            CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileName);
            blockBlob.UploadFromStream(file.InputStream);

            azurePath = String.Format("http://{0}{1}", blockBlob.Uri.DnsSafeHost, blockBlob.Uri.AbsolutePath);

            return azurePath;
        }

        // GET: IncidentTypes
       /// <summary>
       /// Widok główny z listą typów incydentów.
       /// </summary>
       /// <returns>Widok z listą typów incydentów.</returns>
        public ActionResult Index()
        {
            return View(db.IncidentTypes.ToList());
        }

        // GET: IncidentTypes/Details/5
        /// <summary>
        /// Widok detali typu incydentu.
        /// </summary>
        /// <param name="id">ID typu incydentu.</param>
        /// <returns>Widok detali z modelem typu incydentu.</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncidentType incidentType = db.IncidentTypes.Find(id);
            if (incidentType == null)
            {
                return HttpNotFound();
            }
            return View(incidentType);
        }

        // GET: IncidentTypes/Create
       /// <summary>
       /// Widok tworzenia typu incydentu.
       /// </summary>
       /// <returns>Widok.</returns>
        public ActionResult Create()
        {
            return View();
        }

        // POST: IncidentTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Tworzenie typu incydentu.
        /// </summary>
        /// <param name="incidentType">Model typu incydentu z danymi z widoku.</param>
        /// <param name="file">Plik ikony typu incydentu do zapisu w elemencie Blob.</param>
        /// <returns>Widok główny w razie powodzenia, widok dodawania typu incydentu z modelem w przeciwnym wypadku.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeID,Name")] IncidentType incidentType, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    incidentType.IconUrl = saveIconToBlob(file);

                    db.IncidentTypes.Add(incidentType);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(incidentType);
        }

        // GET: IncidentTypes/Edit/5
       /// <summary>
       /// Widok edycji typu incydentu.
       /// </summary>
       /// <param name="id">ID typu incydentu.</param>
       /// <returns>Widok z modelem typu incydentu.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncidentType incidentType = db.IncidentTypes.Find(id);
            if (incidentType == null)
            {
                return HttpNotFound();
            }
            return View(incidentType);
        }

        // POST: IncidentTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edycja typu incydentu.
        /// </summary>
        /// <param name="incidentType">Model typu incydentu z danymi z widoku.</param>
        /// <returns>Widok główny w razie powodzenia, widok z modelem typu incydentu w przeciwnym wypadku.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeID,Name")] IncidentType incidentType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(incidentType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(incidentType);
        }

        // GET: IncidentTypes/Delete/5
       /// <summary>
       /// Widok usuwania typu incydentu.
       /// </summary>
       /// <param name="id">ID typu incydentu.</param>
       /// <returns>Widok z modelem typu incydentu.</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IncidentType incidentType = db.IncidentTypes.Find(id);
            if (incidentType == null)
            {
                return HttpNotFound();
            }
            return View(incidentType);
        }

        // POST: IncidentTypes/Delete/5
        /// <summary>
        /// Usunięcie typu incydentu.
        /// </summary>
        /// <param name="id">ID typu incydentu.</param>
        /// <returns>Widok główny.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IncidentType incidentType = db.IncidentTypes.Find(id);
            db.IncidentTypes.Remove(incidentType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/IncidentsController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    /// <summary>
    /// Kontroler incydentów. Dostępny dla wszystkich oprócz roli Viewer.
    /// </summary>
    [Authorize(Roles="Admin, Emergency, City cleaning, Police, Municipal police, Fire department, Other")]
    public class IncidentsController : Controller
    {
        private Context db = new Context();
        private Context dbt = new Context();
        private ApplicationDbContext appDb = new ApplicationDbContext();

        // GET: Incidents
        /// <summary>
        /// Widok główny z listą incydentów.
        /// </summary>
        /// <returns>Widok z listą incydentów.</returns>
        public ActionResult Index()
        {
            List<IncidentsViewModel> list = new List<IncidentsViewModel>();
            var incidents = db.Incidents;
            if (incidents != null)
            {
                foreach (Incident i in incidents)
                {
                    var services = db.ServiceParticipations.Where(p => p.IncidentId == i.ID);
                    foreach (var s in services)
                    {
                        if (User.IsInRole(s.RoleName) || User.IsInRole("Viewer"))
                        {
                            IncidentsViewModel model = new IncidentsViewModel();
                            IncidentType type = dbt.IncidentTypes.SingleOrDefault(t => t.TypeID == i.TypeID);
                            model.ID = i.ID;
                            model.AddDate = i.AddDate;
                            model.DateOfIncident = i.DateOfIncident;
                            model.TimeOfIncident = i.TimeOfIncident;
                            model.Address = i.Address;
                            model.City = i.City;
                            model.ZipCode = i.ZipCode;
                            model.Lat = i.Lat;
                            model.Long = i.Long;
                            model.Type = i.Type;
                            model.IconUrl = type.IconUrl;
                            model.confirmed = s.confirmed;
                            list.Add(model);
                            break;
                        }
                    }

                }
            }
            return View(list);
        }

        // GET: Incidents/Details/5
        /// <summary>
        /// Widok detali incydentu.
        /// </summary>
        /// <param name="id">ID incydentu.</param>
        /// <returns>Widok detali incydentu lub listę incydentów przy braku uprawnień.</returns>
        public ActionResult Details(int? id)
        {
            bool authorized = false;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incident incident = db.Incidents.Find(id);

            if (incident == null)
            {
                return HttpNotFound();
            }

            IncidentsViewModel viewModel = new IncidentsViewModel();
            viewModel.ID = incident.ID;
            viewModel.About = incident.About;
            viewModel.AddDate = incident.AddDate;
            viewModel.Address = incident.Address;
            viewModel.City = incident.City;
            viewModel.DateOfIncident = incident.DateOfIncident;
            viewModel.Lat = incident.Lat;
            viewModel.Long = incident.Long;
            viewModel.TimeOfIncident = incident.TimeOfIncident;
            viewModel.Type = incident.Type;
            viewModel.ZipCode = incident.ZipCode;
            viewModel.Participants = db.Participants.Where(p => p.incidentID == incident.ID);

            var incidentRoles = db.ServiceParticipations.Where(s => s.IncidentId == id); 
            //(from roles in db.ServiceParticipations where roles.IncidentId == id select roles.RoleId);
            viewModel.Roles = GetRoles();
            foreach (RoleViewModel r in viewModel.Roles)
            {
                foreach (var i in incidentRoles)
                {
                    if (r.RoleId == i.RoleId)
                    {
                        r.Selected = true;
                        if (User.IsInRole(r.RoleName))
                        {
                            authorized = true;
                            viewModel.confirmed = i.confirmed;
                        }
                    }
                }
            }

            if (authorized)  
                return View(viewModel);
            else
                return RedirectToAction("Index");
        }

        /// <summary>
        /// Potwierdzenie incydentu.
        /// </summary>
        /// <param name="id">ID incydentu.</param>
        /// <returns>Przekierowanie do akcji widoku głównego.</returns>
        public ActionResult ConfirmIncident(int id)
        {
            Incident incident = db.Incidents.Find(id);
            if (incident == null)
            {
                return HttpNotFound();
            }
            var part = db.ServiceParticipations.Where(p => p.IncidentId == id);
            foreach(var p in part)
            {
                if (User.IsInRole(p.RoleName))
                {
                    db.ServiceParticipations.Remove(p);
                    ServiceParticipation sp = new ServiceParticipation();
                    sp.IncidentId = id;
                    sp.confirmed = true;
                    sp.RoleId = p.RoleId;
                    sp.RoleName = p.RoleName;
                    db.ServiceParticipations.Add(sp);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Zaprzeczenie udzialu w incydencie.
        /// </summary>
        /// <param name="id">ID incydentu.</param>
        /// <returns>Przekierowanie do akcji widoku głównego incydentów.</returns>
        public ActionResult DenyIncident(int id)
        {
            Incident incident = db.Incidents.Find(id);
            if (incident == null)
            {
                return HttpNotFound();
            }
            var part = db.ServiceParticipations.Where(p => p.IncidentId == id);
            foreach (var p in part)
            {
                if (User.IsInRole(p.RoleName))
                {
                    db.ServiceParticipations.Remove(p);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Incidents/Create
        /// <summary>
        /// Widok tworzenia incydentu.
        /// </summary>
        /// <returns>Widok tworzenia incydentu z modelem uzupełnionym datami oraz listą typów incydentów.</returns>
        public ActionResult Create()
        {
            IncidentsViewModel newIncident = new IncidentsViewModel();
            newIncident.AddDate = DateTime.Today.Date;
            newIncident.DateOfIncident = DateTime.Today.Date;
            newIncident.TimeOfIncident = DateTime.Today.TimeOfDay;
            newIncident.Roles = GetRoles();

            List<SelectListItem> li = new List<SelectListItem>();
            var query = from types in db.IncidentTypes select types;

            foreach (var type in query)
            {
                li.Add(new SelectListItem { Text = type.Name, Value = type.Name });
            }
            ViewData["Types"] = li;

            return this.View(newIncident);
        }

        /// <summary>
        /// Akcja kreowania incydentu z poziomu strony głównej.
        /// </summary>
        /// <param name="address">Adres dodania incydentu.</param>
        /// <returns>Widok kreowania incydentu z uzupełnionym adresem i datami.</returns>
        [HttpPost]
        public ActionResult CreateIncident(string address)
        {
            List<SelectListItem> li = new List<SelectListItem>();
            var query = from types in db.IncidentTypes select types;

            foreach (var type in query)
            {
                li.Add(new SelectListItem { Text = type.Name, Value = type.Name });
            }

            ViewData["Types"] = li;

            IncidentsViewModel newIncident = new IncidentsViewModel();
            newIncident.AddDate = DateTime.Today.Date;
            newIncident.DateOfIncident = DateTime.Today.Date;
            newIncident.TimeOfIncident = DateTime.Today.TimeOfDay;
            newIncident.Roles = GetRoles();

            if (address != "")
            {
                char[] separators = { ',' };
                string[] fullAddress = address.Split(separators);


                if (fullAddress[1].Any(char.IsDigit))
                {
                    newIncident.ZipCode = fullAddress[1].Substring(0, 7).Trim();
                    newIncident.City = fullAddress[1].Substring(8).Trim();
                }
                else
                {
                    newIncident.ZipCode = "XX-XXX";
                    newIncident.City = fullAddress[1].Trim();
                }

                newIncident.Address = fullAddress[0].Trim();
            }

            return View("Create", newIncident);
        }

        // POST: Incidents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Tworzenie incydentu.
        /// </summary>
        /// <param name="incidentView">Model incydentu z widoku.</param>
        /// <returns>Widok główny lub widok tworzenia incydentu w razie błędów.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]

WebApplication1/Views/Incidents/Create.cshtml
@model WebApplication1.Models.IncidentsViewModel

@{
    ViewBag.Title = "Create";
}

<script src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
<script type="text/javascript" src="~/Scripts/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="~/Scripts/markerclusterer.js"></script>
<script type="text/javascript">

    var map;
    var counter = 0;
    var markers = [];
    var marker = new google.maps.Marker;
    var locations = [];
    var geocoder;
    var infowindow = new google.maps.InfoWindow;
    var markerCluster;
    var address;

    function initialize() {
        var mapProp = {
            center: new google.maps.LatLng(52.229491, 21.002137),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        geocoder = new google.maps.Geocoder;
        counter++;

        var input = document.getElementById('pac-input');
        map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(input);

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        autocomplete.addListener('place_changed', function () {
            autocomplete.set('place', void (0));
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                window.alert("Autocomplete's returned place contains no geometry");
                return;
            }

            // If the place has a geometry, then present it on a map.
            if (place.geometry.viewport) {
                map.fitBounds(place.geometry.viewport);
            } else {
                map.setCenter(place.geometry.location);
                map.setZoom(16);  
            }
            placeMarker(place.geometry.location);

        });

        address = "@Html.DisplayFor(Model => Model.Address)" + ", " + "@Html.DisplayFor(Model => Model.City)";
        if (address != ", ")
            geocodeAddress(geocoder, map, address);

        markerCluster = new MarkerClusterer(map, markers);
        google.maps.event.addListener(map, 'click', function (event) {
            placeMarker(event.latLng);
        });

    }

    function geocodeAddress(geocoder, resultsMap, add) {
        address = add;
        geocoder.geocode({ 'address': address }, function (results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
                placeMarker(results[0].geometry.location);
            } else {
                alert('Geocode was not successful for the following reason: ' + status);
            }
        });
    }

    function placeMarker(location) {

        if (marker) deleteMarker(marker.id);
        marker = new google.maps.Marker({
            position: location,
            map: map,
            id: counter
        });
        var address;

        markers.push(marker);
        var deleteButton = '<button id="deleteButton" data-id="' + counter + '">Delete marker</button>';

        document.getElementById('@Html.IdFor(model => model.Lat)').value = location.lat();
        document.getElementById('@Html.IdFor(model => model.Long)').value = location.lng();

        reverseGeocoder(location, function (result, err) {
            address = result;
            address = address.split(',');
            var matches = address[1].match(/\d+/g);
            var zip;
            if (matches != null) {
                zip = address[1].slice(0, 7);
                address[1] = address[1].slice(7);
            }
            else {
                zip = "XX-XXX";
            }

            document.getElementById('@Html.IdFor(model => model.Address)').value = address[0].trim();
            document.getElementById('@Html.IdFor(model => model.City)').value = address[1].trim();
            document.getElementById('@Html.IdFor(model => model.ZipCode)').value = zip.trim();
        });

        var data = 'Counter: ' + counter +
            '<br>What would you like to do?<br><br>' + deleteButton;

        google.maps.event.addListener(marker, 'click', function (event) {
            if (infowindow) infowindow.close();
            infowindow = new google.maps.InfoWindow({ content: data });
            infowindow.open(map, marker);

            var buttonDelete = document.getElementById('deleteButton');
            buttonDelete.onclick = function () {
                deleteMarker(marker.id);
            };
        });
    }

    function deleteMarker(markerId) {

        for (var i = 0; i < markers.length; i++) {
            if (markers[i].id === markerId) {
                markers[i].setMap(null);
                markers.splice(i, 1);
            }
        }
    }

    function reverseGeocoder(latLng, callback) {
        geocoder.geocode({ 'location': latLng }, function (results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
                if (results[0]) {
                    callback(results[0].formatted_address, null);
                } else {
                    callback(null, status);
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });
    }

    function displayLocation() {
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(data.Lat, data.Long),
            map: map
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

<h2>Create</h2>
<h4>Incident</h4>
<div>
    <input id="pac-input" class="controls" type="text"
           placeholder="Search for location...">
</div>
<div id="googleMap" style="height: 500px; width: 100%"></div>


@using (Html.BeginForm("Create", "Incidents"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AddDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfIncident, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfIncident, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfIncident, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfIncident, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfIncident, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOfIncident, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address, htmlAttributes: new { @class = "form-control", @id = "Address" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.City, htmlAttributes: new { @class = "form-control", @id = "City" })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ZipCode, htmlAttributes: new { @class = "form-control", @id = "ZipCode" })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(Model => Model.Type, ViewData["Types"] as List<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @if (HttpContext.Current.User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Add new", "Create", "IncidentTypes")
                }
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control", rows = "10" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Lat, htmlAttributes: new { @class = "form-control", @id = "Lat" })
                @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Long, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Long, htmlAttributes: new { @class = "form-control", @id = "Long" })
                @Html.ValidationMessageFor(model => model.Long, "", new { @class = "text-danger" })
            </div>
        </div>

        @for (var i = 0; i < Model.Roles.Count(); i++)
        {
            var role = Model.Roles[i];
            @Html.HiddenFor(model => model.Roles[i].RoleId)
            @Html.HiddenFor(model => model.Roles[i].RoleName)
            @Html.LabelFor(model => model.Roles[i].RoleName, role.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.CheckBoxFor(model => model.Roles[i].Selected, htmlAttributes: new { @class = "form-control" })
        }
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}




<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Incidents/Delete.cshtml
@model WebApplication1.Models.IncidentsViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfIncident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfIncident)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOfIncident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOfIncident)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.About)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Long)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Long)
        </dd>

        <dt>
            Services
        </dt>
        @for (var i = 0; i < Model.Roles.Count(); i++)
        {
            var role = Model.Roles[i];
            if (role.Selected == true)
            {
                <dd>
                    @Html.DisplayFor(model => model.Roles[i].RoleName, role.RoleName)
                </dd>
            }
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>